import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./Components/Header/Header";
import "./globals.css";
import { Providers } from "./Providers/ApolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="container">
        {children}
        </div>
      </body>
    </html>
    </Providers>
  );
}
